### ISSUE TITLE
Issue when used with superagent-promise...

### ISSUE THREAD

**Issue by resistdesign** [M6Web/superagent-mock#15]
When I use this with `superagent-promise` I get this error: `Unhandled promise rejection TypeError: parserMethod is not a function(…)(anonymous function) @ es6.promise.js:112`

I have no idea why! :P

**Comment by fdubost** [comment]
Sorry but I have no idea too. We don't use `superagent-promise` in our projects for now... :confused:

**Comment by JariInc** [comment]
I was getting similar error but just with plain superagent. I'm guessing this line is the problem https://github.com/M6Web/superagent-mock/blob/master/lib/superagent-mock.js#L104 

For me it was solved just by adding callback to my mock object

```javascript
callback: function (match, data) {
  return data;
}
```

**Comment by resistdesign** [comment]
Weird! I've built my own in-house solution so I'm closing this.

**Comment by khronnuz** [comment]
Why this was closed? this is still a issue for me. Adding callback did not solve it :/

**Comment by khronnuz** [comment]
Ok, to give people more context. After 2h debugging, I finally solved on my end. It was happening because the regex was matching some other url, which had a different 'http method' and no callback.

I think what needs to improve here is to give a more clear error when this kind thing happens: "the url `/foo/bar` does not support 'POST'"

sorry about making noise in the issue.

**Comment by DevSide** [comment]
Solved in 3.4.0 with #60
